import '../tailwind.css'
export { default as Button } from './Button/Button'
export { default as Heading } from './Heading/Heading'
export { default as Text } from './Text/Text'
export { default as Card } from './Card/Card'
export { default as CardBody } from './Card/CardBody'
export { default as CardHeader } from './Card/CardHeader'